name: dbt_run_scheduled_vars
run-name: dbt_run_scheduled_vars

on:
  workflow_dispatch:
  schedule:
    # Runs "every hour" (see https://crontab.guru)
    - cron: '0 */1 * * *'

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template_vars.yml@main
    with:
      dbt_command: >
        dbt seed; dbt run -s tag:helper tag:load+ tag:api --exclude streamline__s3_sync
      environment: workflow_prod
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit 
